name: Build java-cef

on:
  push:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Build
        shell: powershell
        run: |
          mkdir jcef_build; cd jcef_build
          cmake -G "Ninja" -DPROJECT_ARCH=amd64 -DCMAKE_BUILD_TYPE=Release ..
          ninja -j4
          Rename-Item native\Release windows_amd64
          Move-Item native\windows_amd64 windows_amd64
          tar -czf windows_amd64.tar.gz windows_amd64
          $hash = (Get-FileHash -Algorithm SHA256 "windows_amd64.tar.gz").Hash.ToLower()
          Set-Content -Path "windows_amd64.tar.gz.sha256" -Value $hash
      - uses: actions/upload-artifact@v4
        with:
          name: windows_amd64
          path: |
            jcef_build/windows_amd64.tar.gz
            jcef_build/windows_amd64.tar.gz.sha256

  release:
    needs: build-windows
    runs-on: ubuntu-24.04
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: windows_amd64
      - uses: softprops/action-gh-release@v1
        with:
          tag_name: jcef-latest
          files: |
            windows_amd64.tar.gz
            windows_amd64.tar.gz.sha256
